# Site settings
title: Cemre Tok kişisel blog ve kb
email: cemretok {et} gmail {nokta} com
description: > # this means to ignore newlines until "baseurl:"
  Bu blog sitesi edindiğim deneyimleri ve bilgileri paylaşmak için oluşturmuş olduğum bir kb -bilgi bankası- dır.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://cemretok.github.io" # the base hostname & protocol for your site
twitter_username: cemretok
github_username:  cemretok

# Build settings
markdown: kramdown
